### PR TITLE
Adding icons to the frontend assets folder

### PR DESCRIPTION
**Pull request by eprei**
Consider favicons as placeholders since i have not yet been able to generate the definitive ones.

### CODE REVIEW

**Review by RobinBurri — DISMISSED** [review]

**Comment by eprei** [comment]
Thanks for your comments @RobinBurri .

Do you mean that they are not visible enough in the GitHub preview?

If so, it may be because the icons are very small and thin. Also, since they are white and transparent, they can be confused with the background. To verify that they are all there you can open them with the Gimp program. Once inside Gimp, as the icons are vector images, we can assign them the size we want without losing definition in the edges.
When we use them on dark backgrounds (like the ones on the site), they should stand out.

Regarding the .ico file, it is true that it is not well previewed on GitHub, but normally if we open it with the Gimp program we should be able to see that there are three images inside. 

Let me know if any of these comments answer your concerns and if not please let me know one of the files that has the above mentioned problem so I can take a look at it.

**Review by RobinBurri — APPROVED** [review]
OK

**Review by shaolin-peanut — APPROVED** [review]
nice icons let's go

**Review by fire-poy — APPROVED** [review]
Cool!

**Review by t-h2o — APPROVED** [review]

**Pull request merged**
