### PR TITLE
level update and stats updated

### PR DESCRIPTION
**Pull request by shaolin-peanut**
I'm not sure about the math but I think this should make level increase faster as we play. I haven't been able to test playing at home (never lets me play with the same user, even on first try/first connect/after make clean-database), so I'm guessing based on the sample data from seed()

I've put the calculation on the backend, means we need to send less variables and it's cleaner than inline calculations in React Components

More importantly, the nbVictories, xp, and totalPlay variables of the user entities winner and loser are now updated when we create a match object. This works if we pass by the create function in match.service.ts, not if we go directly through typeorm's repository create function like in app.service.ts (which is different and doesn't pass by our code)

### CODE REVIEW

**Review by eprei — COMMENTED** [review]
If you search in vscode 'Math.floor' we can see how we still use the old level calculation in the UserInformation.tsx and UserLambdaInformation.tsx files. Maybe it would be good to also update them to get the same values as the MatchList.tsx element.

**Comment by eprei** [comment]
> I haven't been able to test playing at home (never lets me play with the same user, even on first try/first connect/after make clean-database), so I'm guessing based on the sample data from seed()

Normally to be able to take advantage of the bug that allows us to play against ourselves we have to do the following steps in this order:

- Log in to cosmic pong in a window, create a room.

- log in to another private window and match system.

It is important to first create the room and then login in another window as this is what changes the player's status and allows you to play against yourself.

**Comment by shaolin-peanut** [comment]
> If you search in vscode 'Math.floor' we can see how we still use the old level calculation in the UserInformation.tsx and UserLambdaInformation.tsx files. Maybe it would be good to also update them to get the same values as the MatchList.tsx element.

yeah of course, changing bit later today

**Review by RobinBurri — APPROVED** [review]
👍

**Review by eprei — APPROVED** [review]

**Review by fire-poy — APPROVED** [review]

**Pull request merged**
