### PR TITLE
R real user in front

### PR DESCRIPTION
**Pull request by RobinBurri**
When you sign in with 42, a user is created in the database using the data provided by 42. The user's nickname is set to the login, the avatar URL is set to image.versions.small, and the FT_id is set to the id.

After signing in, the user is redirected to the /profile page. Previously, this page was represented by the ```<Profile />``` component, but now it is represented by the ```<MainProfile />``` component without changing the URL.
(```<Profile />``` was just an empty component returning ```<MainProfile />``` with some css styling so I deleted it).

The MainProfile component includes a loader function, which is used to fetch the user data. This loader function is part of react-router-dom and retrieves the necessary data before rendering the page. Unlike useEffect(), which renders the component first and then fetches the data.

Once the userData is fetched, it is stored in the redux store, making it accessible to everyone. This allows other parts of the application to identify and utilize the user's information.

### CODE REVIEW

**Review by shaolin-peanut — APPROVED** [review]
Bravo! I tried to do this (minus the redux part) but was stuck with import/export problems.
How did you get the UserService/UserRepository to be available in the AuthModule?

I kept getting this after importing/exporting in many different ways, through the module files, different constructors, etc
```bash
our-backend     | [Nest] 94  - 07/10/2023, 12:45:00 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UserService (?). Please make sure that the argument UserRepository at index [0] is available in the AuthModule context.
```

**Review by fire-poy — APPROVED** [review]
ça prendre forme gentiment!

**Comment by eprei** [comment]
Good job!

It will be good to have the real and consistent profile.

Also I find it useful to save the information so that it is accessible from anywhere.

I think that in line 29 of Statistics.tsx the element 'userPosition' is missing.
```
26    <StatisticElement
27        icon={IconRanking}
28        text="Ranking"
29        number={userData.userPosition}
30     />
```

Do you think it will be possible to add the variable 'userPosition: number' to the 'UserData interface'?
This was the previous interface:
```
export interface UserData {
    user: {
        nickname: string
        avatarUrl: string
        nbVictory: number
        totalPlay: number
        xp: number
        TFAEnabled: boolean
    }
    userPosition: number
}
```
Also assign it when you do the loader.

This was the method previously used:
```
    async function getCurrentUser() {
        try {
            const response = await fetch(`http://localhost:8080/api/user/me`, {
                method: ` GET`,
                credentials: `include`,
            })
            if (!response.ok) {
                throw new Error('Failed to fetch user ME')
            }
            const data = await response.json()
            setUserData({ user: data, userPosition: data.userPosition })
            setLoading(false)
        } catch (error) {
            console.log('Error:', error)
        }
    }```

**Comment by RobinBurri** [comment]
> Good job!
> 
> It will be good to have the real and consistent profile.
> 
> Also I find it useful to save the information so that it is accessible from anywhere.
> 
> I think that in line 29 of Statistics.tsx the element 'userPosition' is missing.
> 
> ```
> 26    <StatisticElement
> 27        icon={IconRanking}
> 28        text="Ranking"
> 29        number={userData.userPosition}
> 30     />
> ```
> 
> Do you think it will be possible to add the variable 'userPosition: number' to the 'UserData interface'? This was the previous interface:
> 
> ```
> export interface UserData {
>     user: {
>         nickname: string
>         avatarUrl: string
>         nbVictory: number
>         totalPlay: number
>         xp: number
>         TFAEnabled: boolean
>     }
>     userPosition: number
> }
> ```
> 
> Also assign it when you do the loader.
> 
> This was the method previously used:
> 
> ```
>     async function getCurrentUser() {
>         try {
>             const response = await fetch(`http://localhost:8080/api/user/me`, {
>                 method: ` GET`,
>                 credentials: `include`,
>             })
>             if (!response.ok) {
>                 throw new Error('Failed to fetch user ME')
>             }
>             const data = await response.json()
>             setUserData({ user: data, userPosition: data.userPosition })
>             setLoading(false)
>         } catch (error) {
>             console.log('Error:', error)
>         }
>     }```
> ```

The UserData Interface looks like this now: 

```export interface UserData {
    user: {
        nickname: string
        avatarUrl: string
        nbVictory: number
        totalPlay: number
        xp: number
        TFAEnabled: boolean
        userPosition: number
    }
}```

userPosition is now ok in Statistics.tsx

**Review by eprei — APPROVED** [review]
Quick and efficient solution, I thought it would be more complicated. Good work.

**Pull request merged**
