### PR TITLE
E edit nickname

### PR DESCRIPTION
**Pull request by eprei**
Now the user can change his nickname by
pressing the pencil icon next to his name.
Then enter a text and press enter.

If the user provides a nickname that
already exists in the database he will
receive an error.

If he provides an empty string, he will
receive an error.

If he provides an available nickname, it
will be updated in the database and the
frontend page will be reloaded showing the
new name.

This functionality is not explicitly
protected against SQL injections as no
user data is sanitized. It only validates
your input taking into account that it is
not an empty string. As far as I
understand TypeORM does a great job
protecting us against SQL injections. If
more security is needed we can implement
it.

### CODE REVIEW

**Review by t-h2o — APPROVED** [review]
LGTM

**Review by RobinBurri — APPROVED** [review]
I would be good to give user some feedback in the UI if the nickname change fails.
Now it's only log into the console.

**Review by shaolin-peanut — APPROVED** [review]

**Comment by shaolin-peanut** [comment]
bravo!

**Review by fire-poy — APPROVED** [review]
It seems to me that when you change your nickname, all the page refresh, I think you should put somewhere event.preventDefault()

**Comment by eprei** [comment]
@fire-poy This behavior you are talking about is due to the ```window.location.reload()`` line in the UserInformation.tsx file. It reloads the whole page once the nick is successfully updated. I agree that in the future it can be changed to a more streamlined solution. For now, I wanted to make the feature available as soon as possible so I used the method that was fastest for me.

**Comment by eprei** [comment]
@RobinBurri 

> I would be good to give user some feedback in the UI if the nickname change fails. Now it's only log into the console.

I agree. I admit that I wanted to publish the feature as fast as possible and that's why I left out a standard feature like the little sign that tells you that the nickname is not available. I will gladly add it in a future PR.

**Pull request merged**
