### PR TITLE
changed user.login to user.first_name

### PR DESCRIPTION
**Pull request by RobinBurri**
changed user login attribute to user first_name

### CODE REVIEW

**Review by eprei — APPROVED** [review]

**Review by shaolin-peanut — APPROVED** [review]

**Review by fire-poy — APPROVED** [review]

**Review by fire-poy — COMMENTED** [review]
By firstname did you mean nick or nickname?

**Review by fire-poy — CHANGES_REQUESTED** [review]
By firstname did you mean nick or nickname?

**Comment by shaolin-peanut** [comment]
> By firstname did you mean nick or nickname?

I don't think it's mandatory to have the login as the _default_ name/nickname_ of the user, so we thought of using the first name (prénom) instead, just because it looks better. 
This PR applies that change

**Review by fire-poy — COMMENTED** [review]
To say hello to the user when is loged in I think that is a good idea to call it by their firstname, but for the rest of the site, I thing we should use the nickname. So maybe we could rename every first_name to nick and this way we will only change nickname to first_name in the profile when it will be done, and not otherwise.

**Comment by RobinBurri** [comment]
> To say hello to the user when is loged in I think that is a good idea to call it by their firstname, but for the rest of the site, I thing we should use the nickname. So maybe we could rename every first_name to nick and this way we will only change nickname to first_name in the profile when it will be done, and not otherwise.

What do you mean by nickname?
I don't see any nickname in 42 api user keys.
Screenshot 2023-07-06 at 19 46 34

**Pull request closed without merging**
