### PR TITLE
Delete .env

### PR DESCRIPTION
**Pull request by RobinBurri**
Delete .env file that has wrongly commited

### CODE REVIEW

**Review by fire-poy — APPROVED** [review]

**Comment by fire-poy** [comment]
Il faut l'effacer de l´historique normalement

**Comment by shaolin-peanut** [comment]
> Il faut l'effacer de l´historique normalement

Oui il est encore dans l'historique git

**Comment by RobinBurri** [comment]
have to use a different command to delete the file from history

**Comment by RobinBurri** [comment]
have to use a different command to delete the file from history

**Pull request merged**
