### PR TITLE
two new make commands : cmd-back, cmd-front

### PR DESCRIPTION
**Pull request by RobinBurri**
Two new commands in Makefile for lazy developers.
When you need to pass a command inside a container.

### CODE REVIEW

**Review by eprei — APPROVED** [review]
tip top

**Review by t-h2o — APPROVED** [review]
Why not...

**Review by t-h2o — APPROVED** [review]

**Review by fire-poy — APPROVED** [review]
Looks good to me

**Review by shaolin-peanut — APPROVED** [review]
Okay for me

**Pull request merged**
