### PR TITLE
script: create cmd-back.sh

### PR DESCRIPTION
**Pull request by t-h2o**
# Create script

* create `scripts` folder
* move already existing script into `scripts` folder

## Why ?

automate boring task, en bref,
* execute the command in the container
* format source 
* create a commit with a corresponding commit message

## How use this script

1. clean git status before to execute
2. do the command

## Usage

```
Usage cmd-back.sh:

nest generate:
sh ./cmd-back.sh nestcli <nest_element_type> <name> (<path>)
the <path> is optional

npm install:
sh ./cmd-back.sh npm <package_to_install>
```

### npm install

```bash
  sh ./script/cmd-back.sh npm @nestjs/platform-socket.io
  ```
  
will install the package and create this commit message

```
npm install: @nestjs/platform-socket.io

command used:

docker exec our-backend npm install \
--save @nestjs/platform-socket.io
```

### CODE REVIEW

**Comment by RobinBurri** [comment]
1) It would be nice to be able to choose between install a devDependencies and a dependencies .
2) --save is useless as it's the default.

**Comment by t-h2o** [comment]
> 1. It would be nice to be able to choose between install a devDependencies and a dependencies
```
# npm install --help
[...]
[-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
[...]
```
either `--save-dev` or either the default `--save` ?

**Comment by RobinBurri** [comment]
> > 1. It would be nice to be able to choose between install a devDependencies and a dependencies
> 
> ```
> # npm install --help
> [...]
> [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
> [...]
> ```
> 
> either `--save-dev` or either the default `--save` ?

Exactly.

**Review by RobinBurri — APPROVED** [review]
👍

**Review by eprei — APPROVED** [review]

**Review by fire-poy — APPROVED** [review]

**Review by eprei — APPROVED** [review]

**Review by shaolin-peanut — APPROVED** [review]

**Pull request merged**
